# 🚀 Knowledge Layer Pilot Configuration
# "Making Websites Win" A/B Testing Enhancement

pilot_info:
  name: "Making Websites Win A/B Testing Enhancement"
  version: "1.0"
  start_date: "2025-07-05"
  status: "active"
  target_framework: "ab_testing_framework"

# Pilot scope and limitations
pilot_scope:
  knowledge_sources:
    primary: ["making_websites_win"]
    secondary: []  # No APIs in pilot
    apis_enabled: false
    n8n_enabled: false
  
  target_components:
    - "backend-unified/core/testing/ab_testing_framework.py"
    - "backend-unified/core/testing/real_time_optimizer.py"
    - "backend-unified/src/api/journey/optimization_controller.py"
  
  enhancement_areas:
    - "test_design_validation"
    - "variant_generation"
    - "statistical_significance"
    - "mobile_optimization"
    - "conversion_principles"

# Safety configuration
safety_config:
  enabled: true
  fallback_mode: "original_system"
  confidence_threshold: 0.7
  
  monitoring:
    performance_threshold: 0.2  # 20% degradation triggers rollback
    error_threshold: 3          # 3 consecutive errors trigger rollback
    response_time_max: 5000     # 5 seconds max response time
  
  rollback_triggers:
    - "performance_degradation"
    - "consecutive_errors"
    - "manual_trigger"
    - "confidence_below_threshold"

# Enhancement settings
enhancement_config:
  auto_apply_principles: true
  suggest_improvements: true
  validate_test_design: true
  
  principles_to_apply:
    clarity_over_creativity: true
    friction_reduction: true
    single_element_testing: true
    mobile_first_optimization: true
    statistical_significance: true
  
  confidence_requirements:
    minimum_for_application: 0.7
    recommended_for_auto_apply: 0.8
    required_for_strict_mode: 0.9

# A/B testing specific configuration
ab_testing_config:
  enhancement_hooks:
    test_creation: true
    variant_generation: true
    result_analysis: true
    statistical_validation: true
    mobile_weighting: true
  
  validation_rules:
    enforce_single_element: true
    require_mobile_optimization: true
    minimum_sample_size: 1000
    minimum_confidence: 0.95
    minimum_test_duration: 7  # days
  
  metric_weights:
    mobile_conversion_rate: 2.0
    mobile_engagement: 1.5
    mobile_load_time: 2.0
    desktop_conversion_rate: 1.0

# Logging and monitoring
logging_config:
  enabled: true
  level: "info"
  log_enhancements: true
  log_fallbacks: true
  log_performance: true
  
  metrics_to_track:
    - "enhancement_success_rate"
    - "principle_application_count"
    - "fallback_usage_rate"
    - "performance_impact"
    - "conversion_improvement"

# Validation and testing
validation_config:
  a_b_test_pilot: true
  control_group: "original_system"
  test_group: "knowledge_enhanced"
  
  success_criteria:
    min_improvement: 0.05      # 5% minimum improvement
    statistical_significance: 0.95
    no_performance_degradation: true
    successful_rollback_test: true
  
  test_duration: 30  # days
  sample_size_target: 10000

# Integration points
integration_config:
  knowledge_bridge:
    enabled: true
    initialization_required: true
    fallback_on_failure: true
  
  existing_system:
    modify_core_code: false    # Never modify existing code
    add_external_hooks: true   # Add external enhancement hooks
    preserve_functionality: true
  
  api_endpoints:
    enhancement_status: "/api/knowledge/status"
    rollback_trigger: "/api/knowledge/rollback"
    pilot_metrics: "/api/knowledge/pilot-metrics"

# Expansion planning
expansion_plan:
  phase_2:
    additional_books: ["think_content", "website_conception", "ecommerce_book", "content_design"]
    api_integration: false
    target_date: "2025-08-01"
  
  phase_3:
    api_sources: ["stm_forum", "strackr", "academic_research"]
    analytics_apis: ["apache_druid", "clickhouse"]
    target_date: "2025-09-01"
  
  phase_4:
    n8n_mcp_integration: true
    full_orchestration: true
    target_date: "2025-10-01"

# Emergency procedures
emergency_config:
  rollback_procedure:
    max_duration: "5_minutes"
    steps:
      - "disable_knowledge_enhancement"
      - "clear_enhancement_cache"
      - "restart_affected_services"
      - "validate_original_functionality"
      - "notify_stakeholders"
  
  escalation:
    level_1: "automatic_rollback"
    level_2: "team_notification"
    level_3: "stakeholder_alert"
  
  recovery_plan:
    analysis_required: true
    fix_validation: true
    staged_redeployment: true
    monitoring_period: "24_hours"